### ISSUE TITLE
Why use patternProperties ?

### ISSUE THREAD

**Issue by jonasfj** [alecthomas/jsonschema#2]
I'm curious why do you render `map[string]interface{}` to:
```js
"tags": {
	"type": "object",
	"patternProperties": {
		".*": {
			"type": "object",
			"additionalProperties": true
		}
	}
}
```
instead of:
```js
"tags": {
	"type": "object",
	"additionalProperties": {
		"type": "object",
		"additionalProperties": true
	}
}
```

Slightly unrelated would it possible/feasible to add additional type annotations like `schema:"pattern:'^[a-z]*$'"` for strings, etc or would it be too hard... I guess we would also need a way to validate such `schema` annotations for it to be really fun :)

**Comment by elgris** [comment]
@jonasfj perhaps, `map[string]interface{}` should render to `patternPropeties`, but instead of single pattern `.*` list of map keys should be used. Example:

```
map[string]interface{
  {"prop1": value1},
  {"prop2": "somestring"},
}
```
should render into something like
```
"tags": {
    "type": "object",
    "patternProperties": {
        "prop1": {
            "type": "object",
        },
        "prop2": {
            "type": "string",
        },
    }
}
```

IMHO, there should be a way to define `patternPropeties` as spec says (http://spacetelescope.github.io/understanding-json-schema/reference/object.html#pattern-properties). What do you think?

**Comment by jonasfj** [comment]
Hmm... I must be missing something.. I don't see how to encode patternProperties in a go type.

Similarly, to how there is no way to encode a max for an integer ina go type definition.... Or how we can define that some properties are required, rather than nil.

**Comment by alecthomas** [comment]
I don't recall why, but I'd welcome a PR to fix it.
